#!/bin/bash - 
#===============================================================================
#
#          FILE: postinst
# 
#         USAGE: ./postinst 
# 
#   DESCRIPTION: test
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Anatoly Afanasiev 
#  ORGANIZATION: 
#       CREATED: 01.07.2022 11:57:14
#      REVISION: 0.2
#===============================================================================
set -o nounset                              # Treat unset variables as an error

# ======Логируем возможные ошибки======#
set -E # let shell functions inherit ERR trap

# Trap non-normal exit signals:
# 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
trap err_handler 1 2 3 15 ERR
function err_handler {
local exit_status=${1:-$?}
logger -s -p "syslog.err" -t "ootync.deb" "supersh.deb script '$0' error code $exit_status (line $BASH_LINENO: '$BASH_COMMAND')"
exit $exit_status
}
#производим запуск скрипта сборки пакетов add-pkg.sh в фоновом процессе 
#для предотвращения взаимной блокировки процессов двух dpkg утилит
/opt/add-pkg.sh &
